In [31]:
from pandas import read_excel
import numpy as np

In [32]:
df = read_excel('excel_data.xlsx', names=['A','B'], header=None)

In [33]:
df

A   B
0  1  10
1  2  20
2  3  30
3  4   4
4  5  40
5  6   1
6  7   2

In [34]:
#intersection: items in list A and B
np.intersect1d(df['A'], df['B'])

array([1, 2, 4])

In [35]:
#union of two lists
np.union1d(df['A'], df['B'])

array([ 1,  2,  3,  4,  5,  6,  7, 10, 20, 30, 40])

In [36]:
#only in list A
np.setdiff1d(df['A'], df['B'])

array([3, 5, 6, 7])

In [37]:
#only in list B
np.setdiff1d(df['B'], df['A'])

array([10, 20, 30, 40])